2025-02-18 12:34:10,108 - Error submitting review for Product ID: 1. Error: HTTPSConnectionPool(host='prod.shaqapp.io', port=443): Max retries exceeded with url: /v1/en/users/reviews/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x77e9b45196a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-18 12:34:18,100 - Error submitting review for Product ID: 1. Error: HTTPSConnectionPool(host='prod.shaqapp.io', port=443): Max retries exceeded with url: /v1/en/users/reviews/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x77e9b4519d00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-18 12:38:33,982 - Error submitting review for Product ID: 1. Error: HTTPSConnectionPool(host='prod.shaqapp.io', port=443): Max retries exceeded with url: /v1/en/users/reviews/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x761b9a93d940>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-18 12:38:39,901 - Error submitting review for Product ID: 1. Error: HTTPSConnectionPool(host='prod.shaqapp.io', port=443): Max retries exceeded with url: /v1/en/users/reviews/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x761b9a93ddf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-18 12:38:45,021 - Error submitting review for Product ID: 1. Error: HTTPSConnectionPool(host='prod.shaqapp.io', port=443): Max retries exceeded with url: /v1/en/users/reviews/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x761b9a93e4e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-18 12:38:47,908 - Error submitting review for Product ID: 1. Error: HTTPSConnectionPool(host='prod.shaqapp.io', port=443): Max retries exceeded with url: /v1/en/users/reviews/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x761b9a93ebd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-02-18 12:38:55,878 - Error submitting review for Product ID: 1. Error: HTTPSConnectionPool(host='prod.shaqapp.io', port=443): Max retries exceeded with url: /v1/en/users/reviews/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x761b9a93e2a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
